name: battery-failure
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.2
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-optimize
  - statsmodels
  - xgboost
  - jupyterlab
  - ipykernel
    
# conda env create -f environment.yml

# conda activate battery-failure

